# Model Definition Table
[[model]]
name = "openai-gpt-3.5"
llm_service = "OpenAI"
deployment_name = "gpt-3.5-turbo"
api_key = "OPENAI_API_KEY"

[[model]]
name = "azure-gpt-3.5"
llm_service = "Azure"
deployment_name = "dp02-gpt35"
api_key = "AZURE_OPENAI_API_KEY"
api_version = "2024-02-01"
azure_endpoint = "https://x2.openai.azure.com"

[[model]]
name = "azure-gpt-4o"
llm_service = "Azure"
deployment_name = "dp03-gpt4o"
api_key = "AZURE_OPENAI_API_KEY_USEAST"
api_version = "2024-02-01"
azure_endpoint = "https://x3.openai.azure.com"

